### ISSUE TITLE
Javascript files not automatically being recompiled on save

### ISSUE THREAD

**Issue by icemanind** [failwyn/WebCompiler#55]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.14.8

### Description
When I save a javascript file, I have to manually right click on it and re-compile the file to reproduce the .es5.js and .es5.min.js files. Is there a setting to automatically do this whenever the Javascript file is saved?

**Comment by failwyn** [comment]
Would it be possible to provide a small sample project that I can test this with to see what's going on?

**Comment by icemanind** [comment]
[Sample.zip](https://github.com/failwyn/WebCompiler/files/9925243/Sample.zip)

I attached a minimal example. If you change the "site.js" file and save it, you will notice that the "site.es5.js" file does not update automatically. You have to manually right-click on "site.js" and click "re-compile file" in order to update the "site.es5.js" file.

**Comment by WycoffJohn** [comment]
Im having the same issue with .scss. Had a power failure yesterday, VS has been crashing and WebCompiler was throwing errors. I reinstalled the extension and resetup files and config. Everything works fine manually but will not compile on save. Dont know if this is related to the PC power crash or not.

**Comment by WycoffJohn** [comment]
FYI... I just uninstalled the extension and package, removed all project files (.config and .scss) fully shut down all instances of VS 2022. Reinstalled everything making sure VS was fully loaded/unloaded between steps, added files back and compile on save is not working again. However, upon save the css file updated then I immediately got a BSOD. I realize I have gotten a couple of these since installing this extension a few days ago.

**Comment by failwyn** [comment]
@WycoffJohn Would you be able to check/post the Error Code for the BSOD? I use the extension to compile my SCSS and have never had an issue with compiling on save and have never seen a BSOD. Would it be possible to post a small sample project demonstrating the issue so that I can try to replicate and debug it on my machine?

**Comment by failwyn** [comment]
@icemanind Thanks for the sample, I will do my best to look into this over the weekend.
